spring.application.name=calisthenics
logging.level.root=DEBUG
server.port=8080
spring.messages.basename=messages
spring.web.locale-resolver=fixed
spring.web.locale=en
spring.profiles.active=inmemory
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html